Cargo.toml, src/stream/brotli.rs, src/stream/flate.rs, src/stream/gzip.rs, tests/brotli.rs, tests/deflate.rs, tests/gzip.rs, tests/zlib.rs
Flushing previously didn't guarantee that it would flush out the entire
data.
As part of this the flate and gzip implementations were refactored to a
state machine as I believe this makes them much more understandable,
especially the gzip implementation.
This should fix the issue mentioned at https://github.com/rustasync/tide/pull/194#issuecomment-488900823
New tests added.
=> Fix compressing large chunks

src/stream/brotli.rs, src/stream/deflate.rs, src/stream/flate.rs, src/stream/gzip.rs, src/stream/zlib.rs, tests/brotli.rs, tests/deflate.rs, tests/gzip.rs, tests/zlib.rs
This PR seeks to add support for decompressing streams of encoded bytes under each of the encoding algorithms used.
This is the current progress:
Coming up with a standard pattern of decompressing encoded streams that the library already provides would be valuable for various use cases.
It would also unblock progress on https://github.com/rustasync/tide/pull/194.
Tests are added.
=> Decompressed Stream Support

Cargo.toml, src/stream/mod.rs, src/stream/zstd.rs, tests/utils/mod.rs, tests/zstd.rs
Adds support for compressing/decompressing Zstd over std futures' streams.
Helps contribute to https://github.com/rustasync/async-compression-rs/issues/12. While Zstd isn't exactly well-known in the HTTP compression space, adding support for it would be nice for anyone who wants to use it, as it is comparable to (and at times, faster than) Brotli.
Tests are provided!
=> Zstd support over Streams

src/bufread/deflate.rs, src/bufread/zlib.rs, src/stream/brotli.rs, src/stream/deflate.rs, src/stream/flate.rs, src/stream/gzip.rs, src/stream/zlib.rs
When the readers/streams are known to be some other concrete type in usage it's relatively common to want to call other methods on them that won't affect the compression (e.g. the concrete type may have a method that tells you the current position and total length so you can see how far through the stream you are).
The type system is strong enough to ensure these methods are correct.
=> Add access to the underlying readers/streams for all encoders/decoders

src/stream/zstd.rs
Adds access to the underlying stream for zstd encoders/decoders.
This follows https://github.com/rustasync/async-compression-rs/pull/15#issuecomment-491610634 -- Just wrapping it up real quick. It follows the patterns of the rest of the currently available encoders/decoders
N/A
=> Add access to underlying stream for zstd encoder/decoder

src/stream/deflate.rs, src/stream/flate.rs, src/stream/zlib.rs
Remove `Unpin` bounds from `ZlibEncoder`/`DeflateEncoder`.
More general for potential usecases.
=> Allow using !Unpin streams with zlib/deflate

Cargo.toml
Add the expected metadata for discoverability and linking.
The keywords were mostly pulled from the underlying crates.
=> Add more metadata for the crate

src/stream/zstd.rs, tests/brotli.rs, tests/deflate.rs, tests/gzip.rs, tests/proptest.rs, tests/utils/mod.rs, tests/zlib.rs, tests/zstd.rs
Moves a lot of the existing tests to a macro so that all variants are covered equally by the basic tests.
Found and fixed one bug in the `zstd` encoder when encoding a completely empty stream.
=> Increase test coverage and consistency

Cargo.toml, src/bufread/bzip2.rs, src/bufread/mod.rs, src/codec/bzip2/decoder.rs, src/codec/bzip2/encoder.rs, src/codec/bzip2/mod.rs, src/codec/mod.rs, src/lib.rs, src/stream/bzip2.rs, src/stream/mod.rs, tests/bzip2.rs, tests/proptest.rs, tests/utils/mod.rs
This is an attempt to add bzip2 support to this library. It's at RFC stage, since a few unreleased  bzip2 changes are still needed, c.f. https://github.com/alexcrichton/bzip2-rs/pull/49. 
EDIT: It now works with the latest stable version
Since flate and bzip2 crates are quite similar, I used that as a basis for the implementation. Only details are different.
I added a test case. It still fails, but I'm not entirely sure why. Probably something is wrong at compression, since I can decompress just fine using the crate in a (still private) app. Maybe you have some more insight? 
EDIT: Tests pass fine :).
=> [bzip2] Initial implementation

.travis.yml
This is now the default since https://github.com/rust-lang/cargo/pull/7560, still need to use nightly for `-Z minimal-versions` though.
=> Remove `-Z install-upgrade` for cargo-audit

Cargo.toml, src/stream/generic/decoder.rs, src/stream/generic/encoder.rs
This is a breaking change to the stream interface, but synchronizes the
version of Bytes to what the upcoming hyper release is using.
=> Upgrade bytes to 0.5

src/futures/bufread/generic/decoder.rs, src/futures/bufread/generic/encoder.rs, src/futures/bufread/macros/decoder.rs, src/futures/bufread/macros/encoder.rs, src/futures/write/buf_writer.rs, src/futures/write/generic/decoder.rs, src/futures/write/generic/encoder.rs, src/futures/write/macros/decoder.rs, src/futures/write/macros/encoder.rs, src/stream/generic/decoder.rs, src/stream/generic/encoder.rs, src/stream/macros/decoder.rs, src/stream/macros/encoder.rs
This change allows downstream types to depend on `async_compression` types without extra trait bounds.
Currently, users need to write something like the following:
```rust
struct Foo<S: Stream<Item = Result<Bytes>>> {
stream: GzipDecoder<S>,
// ...
}
```
After this change, it becomes:
```rust
struct Foo<S> {
stream: GzipDecoder<S>,
// ...
}
```
The trait bounds are still enforced on the constructors, so they still prevent you from creating `*Decoder<T>` or `*Encoder<T>` values when the required trait bounds are not satisfied.
=> Remove trait bounds on type definitions

Cargo.toml, src/codec/brotli/decoder.rs, src/codec/brotli/encoder.rs, src/lib.rs, src/macros.rs, tests/utils/mod.rs
Fixes #39.
I removed `brotli2` because it is severely outdated. It uses a version of googles `brotli` that is almost 3 years old.
If requested I can add `brotli2`, but would like to have some guidance on naming the features.
=> Replace `brotli2` with `brotli`.

src/lib.rs
First thanks for making this! We're very happily migrating some sync code to use this within a hyper server.
Since we're using this crate in a high-performance speed and size sensitive web service, we need to tune our underlying algorithm qualities beyond just `Fastest`, `Best` and `Default`. For example, Brotli's default value is the same as best, which is much too slow for us, but `Fastest` is basically a no-op when measuring compression ratios.
This PR exposes a `Level::Precise(u32)` option to allow specific tuning of the underlying encoder's quality; this works for all algorithms except bzip2, where it just uses `Default`. In basic testing it works like a charm.
I was unable to build tests on latest `master`, so I'm not sure how to begin testing.
=> RFC: Add Level::Precise to allow precise quality level specification.

src/lib.rs
Technically a breaking change (same with #86), but I have verified that all current rev-deps don't try and match on this (and if any do, I'll yank and do a proper breaking release).
=> Make Level non-exhaustive

.github/workflows/coverage.yml, .github/workflows/exhaustive.yml, Cargo.lock, Cargo.toml, src/futures/mod.rs, src/lib.rs, src/tokio_02/bufread/generic/decoder.rs, src/tokio_02/bufread/generic/encoder.rs, src/tokio_02/bufread/generic/mod.rs, src/tokio_02/bufread/macros/decoder.rs, src/tokio_02/bufread/macros/encoder.rs, src/tokio_02/bufread/macros/mod.rs, src/tokio_02/bufread/mod.rs, src/tokio_02/mod.rs, src/tokio_02/write/buf_write.rs, src/tokio_02/write/buf_writer.rs, src/tokio_02/write/generic/decoder.rs, src/tokio_02/write/generic/encoder.rs, src/tokio_02/write/generic/mod.rs, src/tokio_02/write/macros/decoder.rs, src/tokio_02/write/macros/encoder.rs, src/tokio_02/write/macros/mod.rs, src/tokio_02/write/mod.rs, tests/proptest.rs, tests/utils/mod.rs, tests/utils/tokio_02_ext/copy_buf.rs, tests/utils/tokio_02_ext/interleave_pending.rs, tests/utils/tokio_02_ext/limited.rs, tests/utils/tokio_02_ext/mod.rs, tests/utils/track_closed.rs
Terribad copy-paste job, but any cleanup to reduce duplication shouldn't affect public API so easy path is to get this in first.
fixes #57
=> Add support for tokio v0.2

Cargo.lock
does the minimal amount to fix the `cargo deny advisories` CI job
=> chore: update locked vulnerable deps

CHANGELOG.md
To keep notes of public API changes.
I have [a version bump script](https://github.com/actix/actix-web/blob/master/scripts/bump) that make maintaining this file very easy.
=> docs: add CHANGELOG file

src/lib.rs, src/macros.rs
`doc_auto_cfg` is in a good enough state now. Also fixes some attribute positions so that feature combinations get shown correctly.
blocked on #152
=> use automatic doc cfg for features

src/futures/bufread/macros/decoder.rs, src/futures/bufread/macros/encoder.rs, src/futures/mod.rs, src/futures/write/macros/decoder.rs, src/futures/write/macros/encoder.rs, src/macros.rs, src/tokio/bufread/macros/decoder.rs, src/tokio/bufread/macros/encoder.rs, src/tokio/mod.rs, src/tokio/write/macros/decoder.rs, src/tokio/write/macros/encoder.rs
also fixes build when some features are not enabled (for some reason not picked up by exhaustive feature powerset check)
=> refactor: use concat in doc comments

Cargo.toml
=> chore: remove implicit empty default feature

src/codec/zstd/encoder.rs, src/lib.rs, src/macros.rs
This allows enabling parameters such as long-distance matching mode or rsyncable mode.
=> Add ZstdEncoder::with_quality_and_params to enable compression parameters

.github/workflows/base.yml, .github/workflows/coverage.yml, .github/workflows/exhaustive.yml, .github/workflows/nightly.yml
Imo this is plenty fast enough and any further changes would only complicate our simple CI setup for no to negligible gain.
=> Use `cargo-nextest` to speedup testing

CHANGELOG.md, src/brotli.rs, src/lib.rs, src/macros.rs, src/zstd.rs
closes #239
(none)
(none)
```
pub mod brotli
pub struct brotli::EncoderParams
pub fn brotli::EncoderParams::block_size(self, block_size: i32) -> Self
pub fn brotli::EncoderParams::size_hint(self, size_hint: usize) -> Self
pub fn brotli::EncoderParams::text_mode(self) -> Self
pub fn brotli::EncoderParams::window_size(self, window_size: i32) -> Self
impl core::marker::Copy for brotli::EncoderParams
impl core::clone::Clone for brotli::EncoderParams
impl core::cmp::Eq for brotli::EncoderParams
impl core::cmp::PartialEq<brotli::EncoderParams> for brotli::EncoderParams
impl core::fmt::Debug for brotli::EncoderParams
impl core::marker::Send for brotli::EncoderParams
impl core::marker::Sync for brotli::EncoderParams
impl core::marker::Unpin for brotli::EncoderParams
impl …
```
=> Brotli encoder params

.github/workflows/exhaustive.yml, Cargo.toml
Tested with:
cargo +nightly update -Zminimal-versions; cargo check --all-features
See https://github.com/rust-lang/flate2-rs/pull/221
(And #85 would be nice)
=> Fix a minimum-versions issue

src/codec/lzma/decoder.rs, src/codec/xz/decoder.rs, src/codec/xz2/decoder.rs, src/macros.rs
xz2 decoders are by default configured with a memory limit value of u64::max. This is problematic on targets where there is limited memory available for decoding. e.g. one could run out of memory. By exposing an additional function call `XzDecoder::with_memlimit(..)` and `LzmaDecoder::with_memlimit(..)` users can initialize a decoder with a given memory limit.
Consequently specifying a too low value means the decoder will fail to decompress. On this occasion the decoder will return an `io::Error::Custom` value with the message "MemLimit" to signal it needs to be configured with more memory.
This error is propagated by the chosen interface, `AsyncBufRead` or `AsyncWrite`, therefore no additional error handling has to be implemented to handle this "side effect"
=> expose memlimit settings for xz2 decoders

src/codec/bzip2/decoder.rs, src/codec/bzip2/encoder.rs, src/codec/gzip/encoder.rs, src/codec/gzip/header.rs, src/codec/xz2/decoder.rs, src/codec/xz2/encoder.rs, src/futures/write/generic/decoder.rs, src/futures/write/generic/encoder.rs, src/tokio/write/generic/decoder.rs, src/tokio/write/generic/encoder.rs
I hope you'll consider this PR for inclusion in a patch release.
This PR replaces panics with errors. This is important when the crate is being used in, for example, a long running server process where handling an error is preferred to a panic.
This should help with issues such as: #188 or #246
=> Replacing panics with errors improves the usability of the crate

CHANGELOG.md, src/codec/gzip/decoder.rs, src/futures/bufread/generic/decoder.rs
=> flush data still available in the decoder when no input (#123)

src/zstd.rs
#285 adds wrapper types for `DParameter`, but uses glob imports to pull the `libzstd::stream::raw::{C,D}Parameter` types into scope. This introduces a _possible_ forwards-compatability hazard if `libzstd` were to introduce `{C,D}Parameter` enum variants with the same name.
This PR uses explicit paths for referencing these wrapper types, to avoid this possibility.
=> Use explicit paths rather than glob imports for zstd wrapper types.

Cargo.toml
There were few changes between 6.0.0 and 7.0.0, and it looks like https://github.com/dropbox/rust-brotli/commit/41cadaabb6c650ae518b30509a5fbe43ca8cfab9 was the only breaking one. I confirmed that `cargo test --all-features` still passes.
=> Update brotli to 7.0

src/tokio/bufread/generic/decoder.rs
Unlike zlib, miniz_oxide consumes data into internal state
even if there is not enough space in the output buffer.
Next time poll_fill_buf() is called we should try
to decode from internal state even if no new compressed data
was read.
This change is a port of fix <https://github.com/Nullus157/async-compression/issues/123> (commit https://github.com/Nullus157/async-compression/commit/22ed0ac4caf5d60628ff8836dd1dc2d3289cf43f) from `futures` to `tokio`.
=> fix(tokio): attempt to decode from internal state even if nothing was read

src/futures/bufread/generic/decoder.rs, src/tokio/bufread/generic/decoder.rs
=> Fix panic when decoding

src/futures/bufread/generic/decoder.rs, src/futures/bufread/generic/encoder.rs, src/futures/bufread/macros/decoder.rs, src/futures/bufread/macros/encoder.rs, src/futures/write/buf_writer.rs, src/futures/write/generic/decoder.rs, src/futures/write/generic/encoder.rs, src/futures/write/macros/decoder.rs, src/futures/write/macros/encoder.rs, src/tokio/bufread/generic/decoder.rs, src/tokio/bufread/generic/encoder.rs, src/tokio/bufread/macros/decoder.rs, src/tokio/bufread/macros/encoder.rs, src/tokio/write/buf_writer.rs, src/tokio/write/generic/decoder.rs, src/tokio/write/generic/encoder.rs, src/tokio/write/macros/decoder.rs, src/tokio/write/macros/encoder.rs
Closes https://github.com/Nullus157/async-compression/issues/296
=> Pass through `AsyncRead` and `AsyncWrite` traits

src/futures/write/generic/decoder.rs, src/futures/write/generic/encoder.rs, src/futures/write/macros/decoder.rs, src/futures/write/macros/encoder.rs, src/tokio/write/generic/decoder.rs, src/tokio/write/generic/encoder.rs, src/tokio/write/macros/decoder.rs, src/tokio/write/macros/encoder.rs
=> Pass through `AsyncBufRead` trait for write-based encoders/decoders

src/futures/bufread/generic/decoder.rs, src/tokio/bufread/generic/decoder.rs
Fixed #298
This PR changes the decoder `do_poll_read` impl, to not advance the buffer on first flush.
The panic is because the decoder try to advance the buffer before polling the underlying buf reader.
~~In this PR I tried a different fix, by making sure `buf.consume` is always called, even on error.
I suspect that previously we didn't consume the buffer on error, and that might have caused the same data to be decompressed again.~~
~~I can't think of anywhere else that could fail, the decoder implementation looks alright.~~
=> Fix panic: cannot consume from pending buffer

src/lib.rs
Previously, the clamp range was from "fastest" to "best" (1-9). This PR changes the range to start from "none" (0) to allow for no compression.
Closes #313
=> Adjust `Level::Precise` clamp range for flate2

src/tokio/write/generic/encoder.rs
Once a flush has been started some encoders (for example xz2) require that the flush is completed before writing more data.
=> encoder: ensure that flush is finished

src/codec/flate/encoder.rs
There may be data remaining in the internal state of the encoder.
Without the fix on a second call to flush() when the caller makes space in the output buffer we will write nothing into the buffer.
=> fix(flate encoder): do not mark internal state as flushed if we ran out of buffer space

Cargo.toml, src/codec/lz4/decoder.rs, src/codec/lz4/encoder.rs, src/codec/lz4/mod.rs, src/codec/mod.rs, src/futures/bufread/generic/encoder.rs, src/futures/write/generic/encoder.rs, src/lib.rs, src/lz4.rs, src/macros.rs, src/tokio/bufread/generic/encoder.rs, src/tokio/write/generic/encoder.rs, src/util.rs, tests/artifacts/lib.rs, tests/lz4.rs, tests/proptest.rs, tests/utils/algos.rs
This PR adds LZ4 support, drawing from the gzip (encoder) and bzip2 (decoder) implementations.
=> feat: add lz4 support

src/codec/deflate/encoder.rs, src/macros.rs
Expose the underlying `total_in` and `total_out` methods in `DeflateEncoder`, in the same fashion as #278.
=> Expose total_in/total_out in DeflateEncoder

.github/workflows/wasi.yml, Cargo.toml, src/codec/xz/decoder.rs, src/codec/xz/encoder.rs, src/codec/xz2/decoder.rs, src/codec/xz2/encoder.rs, src/lib.rs, src/macros.rs, tests/utils/algos.rs, tests/xz.rs
Adds `XzEncoder::parallel` and `XzDecoder::parallel` methods that enable multi-threaded compression and decompression.
Care must be taken not that call `flush()` on the encoder in quick succession, as this would severely impact multi-threaded compression performance.
Gated by the `xz-parallel` crate feature.
=> xz: add multi-thread support

src/lib.rs
=> fix(zstd): fastest level now does compression

crates/async-compression/README.md
Stop using an outdated crate version for the Deps.rs badge.
=> Update Deps.rs badge

crates/async-compression/src/futures/bufread/generic/encoder.rs, crates/async-compression/src/tokio/bufread/generic/encoder.rs, crates/async-compression/tests/utils/impls.rs
Currently flush() is not getting called so compressed output is not returned to the client the encoder until input is fully read(). In my use case, flushing more often is necessary as otherwise it appears to the client the data gets 'buffered'.
There's been a previous PR here and some discussion https://github.com/Nullus157/async-compression/pull/155 but appears to be abandonded so if there's interest in this fix, this PR tries this again.
The tests are passing with this change.
=> Flush compressed data out of encoders more often

crates/compression-codecs/src/lib.rs
It's impossible to use codecs without also importing core
=> Re-export core in codecs
