Nullus157/async-compression

- Cargo.toml
- LICENSE-APACHE
- LICENSE-MIT
- README.md
@fairingrey I'll need your signoff to retroactively license your changes so far under `MIT OR Apache-2.0`.
> Add license files and trivial readme

- src/stream/gzip.rs
- src/stream/mod.rs
- tests/gzip.rs
Adds support for encoded Gzip streams.
Tests are added.
> add gzip stream support

- src/stream/gzip.rs
Makes working with a Gzip stream easier to work with (gets rid of the `Chain` and appends the header in the poll logic instead).
> make gzip stream easier to work with

- Cargo.toml
- tests/brotli.rs
- tests/deflate.rs
- tests/gzip.rs
- tests/proptest.rs
- tests/utils/mod.rs
- tests/zlib.rs
Adds automatically generated tests based on [`proptest`](https://altsysrq.github.io/proptest-book/intro.html) to ensure arbitrary compression works. Also refactors a lot of the existing tests to use common utilities to simplify them.
I'll probably move `PendRead` and `PendStream` upstream to `futures-test` since they're likely useful in other testing, so they can be pulled directly from there on the next release. (https://github.com/rust-lang-nursery/futures-rs/pull/1576)
More thorough testing.
> Add proptest tests and test utilities module

- src/bufread/deflate.rs
- src/bufread/zlib.rs
- src/lib.rs
- src/stream/brotli.rs
- src/stream/deflate.rs
- src/stream/flate.rs
- src/stream/gzip.rs
- src/stream/zlib.rs
- src/stream/zstd.rs
Adds debug impls for everything and enables some warnings that should be followed by most crates.
> Enable more generally useful warnings

- Cargo.toml
- src/bufread/mod.rs
- src/lib.rs
- src/stream/mod.rs
- src/stream/zstd.rs
- tests/utils/mod.rs
See the updated docs in lib.rs for details on the design.
This allows users to only pay compilation cost for the compressions and usecases they care about (e.g. Tide can now stop compiling the `bufread` implementations it doesn't use).
> Add features to cover different usecases

- Cargo.toml
- src/bufread/deflate.rs
- src/bufread/zlib.rs
- src/lib.rs
- src/stream/brotli.rs
- src/stream/deflate.rs
- src/stream/gzip.rs
- src/stream/zlib.rs
- src/stream/zstd.rs
Not the greatest rendering, but getting this feature more widely used might incite someone to improve it.
> Use doc(cfg) to document features

- .travis.yml
- Cargo.toml
> Update futures and nightly

- src/bufread/deflate.rs
- src/bufread/zlib.rs
- src/lib.rs
- src/stream/brotli.rs
- src/stream/deflate.rs
- src/stream/gzip.rs
- src/stream/zlib.rs
- src/stream/zstd.rs
- src/unshared.rs
- src/util.rs
> Make ZstdEncoder/Decoder Sync

- src/stream/gzip.rs
- tests/gzip.rs
> Fix decompressing over 8K of gzip data

- src/bufread/generic/decoder.rs
- src/bufread/generic/encoder.rs
- src/bufread/generic/mod.rs
- src/codec/brotli/decoder.rs
- src/codec/brotli/encoder.rs
- src/codec/deflate/decoder.rs
- src/codec/deflate/encoder.rs
- src/codec/flate/decoder.rs
- src/codec/flate/encoder.rs
- src/codec/gzip/decoder.rs
- src/codec/gzip/encoder.rs
- src/codec/mod.rs
- src/codec/zlib/decoder.rs
- src/codec/zlib/encoder.rs
- src/codec/zstd/decoder.rs
- src/codec/zstd/encoder.rs
- src/stream/generic/decoder.rs
- src/stream/generic/encoder.rs
- src/util.rs
Moves the header and footer handling into the codec. Also includes a refactor to use `PartialBuffer` for all codecs.
Closes #35
> Refactor GZIP header and footer handling

- Cargo.toml
- src/codec/gzip/decoder.rs
- src/codec/gzip/header.rs
- src/codec/gzip/mod.rs
- src/util.rs
- tests/gzip.rs
Parse and discard extended gzip header data
fixes #36
> Add parsing of extra gzip header data

- .travis.yml
> Change branches built by travis for bors

- Cargo.toml
- src/bufread/generic/decoder.rs
- src/bufread/generic/encoder.rs
- src/bufread/macros/decoder.rs
- src/bufread/macros/encoder.rs
- src/stream/generic/decoder.rs
- src/stream/generic/encoder.rs
- src/stream/macros/decoder.rs
- src/stream/macros/encoder.rs
Changes: https://github.com/taiki-e/pin-project/releases/tag/v0.4.0
> Update pin-project to 0.4

- Cargo.toml
- src/bufread/brotli.rs
- src/bufread/deflate.rs
- src/bufread/generic/decoder.rs
- src/bufread/generic/encoder.rs
- src/bufread/gzip.rs
- src/bufread/macros/decoder.rs
- src/bufread/macros/encoder.rs
- src/bufread/mod.rs
- src/bufread/zlib.rs
- src/bufread/zstd.rs
- src/lib.rs
- src/stream/brotli.rs
- src/stream/deflate.rs
- src/stream/generic/decoder.rs
- src/stream/generic/encoder.rs
- src/stream/gzip.rs
- src/stream/macros/decoder.rs
- src/stream/macros/encoder.rs
- src/stream/mod.rs
- src/stream/zlib.rs
- src/stream/zstd.rs
> Reduce futures dependencies

- .travis.yml
- Cargo.toml
- README.md
- src/lib.rs
- tests/bzip.rs
- tests/proptest.rs
- tests/utils/mod.rs
Disables all features by default and updates documentation for them.
closes #46
> Change default features

- Cargo.toml
- src/bufread/generic/decoder.rs
- src/bufread/generic/encoder.rs
- src/bufread/macros/decoder.rs
- src/bufread/macros/encoder.rs
- src/stream/generic/decoder.rs
- src/stream/generic/encoder.rs
- src/stream/macros/decoder.rs
- src/stream/macros/encoder.rs
- src/write/buf_writer.rs
- src/write/generic/decoder.rs
- src/write/generic/encoder.rs
- src/write/macros/decoder.rs
- src/write/macros/encoder.rs
> Move to pin-project-lite

- Cargo.toml
> Update repository url metadata

- Cargo.toml
- src/codec/brotli/decoder.rs
- src/codec/brotli/encoder.rs
- src/codec/bzip2/decoder.rs
- src/codec/bzip2/encoder.rs
- src/codec/deflate/decoder.rs
- src/codec/deflate/encoder.rs
- src/codec/flate/decoder.rs
- src/codec/flate/encoder.rs
- src/codec/gzip/decoder.rs
- src/codec/gzip/encoder.rs
- src/codec/gzip/header.rs
- src/codec/mod.rs
- src/codec/zlib/decoder.rs
- src/codec/zlib/encoder.rs
- src/codec/zstd/decoder.rs
- src/codec/zstd/encoder.rs
- src/stream/generic/decoder.rs
- src/stream/generic/encoder.rs
- src/util.rs
- tests/utils/mod.rs
> Yield None after Err(_) for stream adaptors

- Cargo.toml
- src/codec/lzma/decoder.rs
- src/codec/lzma/encoder.rs
- src/codec/lzma/mod.rs
- src/codec/mod.rs
- src/codec/xz/decoder.rs
- src/codec/xz/encoder.rs
- src/codec/xz/mod.rs
- src/codec/xz2/decoder.rs
- src/codec/xz2/encoder.rs
- src/codec/xz2/mod.rs
- src/lib.rs
- src/macros.rs
- tests/lzma.rs
- tests/proptest.rs
- tests/utils/mod.rs
- tests/xz.rs
Hi, I attempted to add lzma support to your library as I needed it for my own usecase.
I hope I caught all the areas (tests, docs, etc) in which I had to add support for a new encoder/decoder, if not please let me know.
> add support for lzma

- src/codec/brotli/decoder.rs
- src/codec/bzip2/decoder.rs
- src/codec/deflate/decoder.rs
- src/codec/flate/decoder.rs
- src/codec/gzip/decoder.rs
- src/codec/lzma/decoder.rs
- src/codec/mod.rs
- src/codec/xz/decoder.rs
- src/codec/xz2/decoder.rs
- src/codec/zlib/decoder.rs
- src/codec/zstd/decoder.rs
- src/futures/bufread/generic/decoder.rs
- src/futures/bufread/macros/decoder.rs
- src/stream/generic/decoder.rs
- src/stream/macros/decoder.rs
- tests/utils/mod.rs
- tests/xz.rs
> Add opt-in support for decoding multi-member compressed streams

- src/futures/write/generic/decoder.rs
- tests/utils/mod.rs
- tests/utils/track_closed.rs
Tests and finishes fixing issues from #91
> Test and fix flushing

- .github/dependabot.yml
Signed-off-by: Jiahao XU <Jiahao_XU@outlook.com>
> dependabot: only update deps on breaking changes

- README.md
> docs: add deps and license badge

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
@NobodyXu @Nemo157 Are there any other breaking changes from the open issues/PRs that we'd like to get in to a v0.4.0 release?
Draft release: https://github.com/Nullus157/async-compression/releases/tag/untagged-8fbf8524f930fef3d14c
> async-compression 0.4.0

- CHANGELOG.md
- Cargo.toml
- src/lib.rs
- src/macros.rs
> Add new feature `zstdmt` for `zstd::CParameter::nb_workers`

- src/futures/bufread/macros/decoder.rs
- src/futures/write/macros/decoder.rs
- src/macros.rs
- src/tokio/bufread/macros/decoder.rs
- src/tokio/write/macros/decoder.rs
> make it visually clear that inner param is shared 

- CHANGELOG.md
- Cargo.toml
- README.md
https://github.com/Nullus157/async-compression/releases/tag/untagged-d8896600d2af24d21510
> prepare release 0.4.1

- CHANGELOG.md
- Cargo.toml
- src/codec/deflate64/decoder.rs
- src/codec/deflate64/mod.rs
- src/codec/mod.rs
- src/lib.rs
- src/macros.rs
Closes #237
Because I could not find deflate64 compression implementation, this only adds encode support for deflate64
> feat: deflate64 decompression (decode-only) support

- CHANGELOG.md
- Cargo.toml
- README.md
https://github.com/Nullus157/async-compression/releases/tag/untagged-08c576b47e21f174d527
> prepare release 0.4.2

- CHANGELOG.md
- Cargo.toml
- README.md
- src/brotli.rs
> feat: impl Default for brotli::EncoderParams

- CHANGELOG.md
- Cargo.toml
- src/codec/xz2/decoder.rs
- src/codec/xz2/encoder.rs
- src/macros.rs
https://github.com/Nullus157/async-compression/releases/edit/untagged-8e9bfc7dface9d665f45
> prepare release 0.4.5

- CHANGELOG.md
- Cargo.toml
- README.md
draft release https://github.com/Nullus157/async-compression/releases/tag/untagged-3307b223ded9d43f19b9
> chore: prepare release 0.4.6

- CHANGELOG.md
- Cargo.toml
- README.md
- bump dep brotli from 3.3 to 4.0
> Release async-compression 0.4.8

- .github/workflows/release-pr.yml
- .github/workflows/release.yml
Maintainer can trigger release process by going to actions -> Open release pr -> Run workflow
> CI: Support release on workflow triggering

- src/futures/bufread/generic/decoder.rs
- src/tokio/bufread/generic/decoder.rs
Reverts Nullus157/async-compression#299
> Revert "Fix panic when decoding"
